# Generated by Django 5.2.2 on 2025-06-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_role_artistprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artistprofile",
            name="followers",
        ),
        migrations.AddField(
            model_name="artistprofile",
            name="followers_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
