# Generated by Django 5.2.2 on 2025-06-15 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "cover",
                    models.ImageField(blank=True, null=True, upload_to="album_covers/"),
                ),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Album",
                "verbose_name_plural": "Albums",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="tracks/"),
                ),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "cover",
                    models.ImageField(blank=True, null=True, upload_to="track_covers/"),
                ),
                ("plays_count", models.PositiveIntegerField(default=0)),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracks",
                        to="music.album",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Track",
                "verbose_name_plural": "Tracks",
            },
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=100)),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to="playlist_covers/"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tracks",
                    models.ManyToManyField(
                        blank=True, related_name="playlists", to="music.track"
                    ),
                ),
            ],
            options={
                "verbose_name": "Playlist",
                "verbose_name_plural": "Playlists",
            },
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=["artist", "title"], name="music_track_artist__7f26ba_idx"
            ),
        ),
    ]
